### PR TITLE
Modify fountain sprites

### PR DESCRIPTION
**Pull request by zabala6**
- changed coloring to match other cast iron items
- changed design, to move fountain snout from middle to side, in order to match the transition from empty fountain to full fountain
- removed bronze coloring from full fountain water

preview

### CODE REVIEW

**Comment by sidraba** [comment]
Sound for removing water from fountain need to be fixed, currently it's creation sound of fountain.

**Comment by connorhsm** [comment]
There's a little button (on desktop) in the top right, near "reviewers" for you to mark this PR as a draft until you're ready 🙂

**Comment by sidraba** [comment]
> Sound for removing water from fountain need to be fixed, currently it's creation sound of fountain.

Resolved in new commits. Tested on on my machine and worked like a clock. Such a great job!

**Comment by zabala6** [comment]
Summary of changes:
- Added three fountain variants (boy with bowl, elephant and frog)
- Most of the transitions are done by categories so it is more easier to maintain it
- Initial sound of creating fountain is only played when the fountain is build from three cylinders and their variants are switched using a hammer
- Old fountain is overwritten by fountain boy with bowl

Preview of fountains:
screen00002

**Review by risvh — DISMISSED** [review]

**Review by risvh — APPROVED** [review]

**Pull request merged**
