### PR TITLE
Fix positioning and sounds for backpack and poipack

### PR DESCRIPTION
**Pull request by zabala6**
Fixing annoying positioning inconsistency of Poipack sprites and slots.
This solution is fixing Poipack with something based of (regular) Poipack.
poipack_positioning

### CODE REVIEW

**Review by connorhsm — CHANGES_REQUESTED** [review]
@Zabala6 Please avoid merge commits into feature branches like this one. You should instead rebase from master. You can do this once a PR is open with buttons to "resolve conflict" shown at the bottom or at any time via the CLI using:
```
git checkout my-branch
git rebase master
git push --force-with-lease
```

**Review by connorhsm — DISMISSED** [review]
Nice work, thanks. Please let @risvh merge when ready.

**Comment by sidraba** [comment]
Tested on my local, huge rework! Loved consistent backpack slot placement! And consistent sounds are nice!

Room for improvement:
1. when poipack/backpack is on floor then tool removal sound is different than when it' s equiped. I'd expect them to be the same.
2. Backpack with soil has wrong sound.
3. When backpack/poipack is put down it has different sound than interaction. Not sure if that is the right sound. It's very "clicky".
4. creation of fishing rod (both rods) has animation issue (thread is jumping after decay).
5. when creating tools decay goes to "probably steel axe use 4" (for all tools)

**Comment by zabala6** [comment]
Thank you for your review @sidraba!
I fixed points 2,4 and 5.
Points 1 and 3 seams correct for me so I am not fixing it. It is up to @risvh to decide what is correct.

**Review by risvh — DISMISSED** [review]
Thank you

**Review by risvh — APPROVED** [review]

**Pull request merged**
