### PR TITLE
Add ability to plant swamp trees.

### PR DESCRIPTION
**Pull request by SenMooo**
This request adds Willow and Bald Cypress cuttings as well as the ability to add these trees to the tree pits.

As to why they should be added, here is my short thesis on the subject.

**-Enhancing Aesthetics of Swamp Biomes:**

Swamp biomes can often look barren and uninviting due to the lack of vegetation. Plantable swamp trees would allow players to add greenery and life to these areas, making them more visually appealing and realistic within the game world.

**-Reducing the anxiety of nature lovers:**

Swamp areas are currently the go-to location for collecting firewood and logs, which can be a constant source of anxiety for players who prefer to maintain the natural surroundings of their towns. Personally, I have witnessed numerous arguments related to this issue.

**-Adding Decorative Options:**

Plantable swamp trees would provide players with additional decorative options for landscaping and town-building. They can be used to create lush gardens or atmospheric settings within towns.

**Encouraging Creative Building:**

Allowing players to plant swamp trees encourages creativity in town-building and landscaping. Players can experiment with different layouts, designs, and combinations of swamp vegetation to personalize their surroundings.

The thesis has been rendered more readable with the assistance of our helpful, though not entirely sentient algorithm.

### CODE REVIEW

**Review by sidraba — CHANGES_REQUESTED** [review]
That's a lot of hard work on this PR—great job! We reviewed it together with @Zabala6 , and it's clear you've put a lot of effort into it. Everything seems to work as expected, although we only tested sprinklers minimally. Here are some key highlights:

**Functionality**: The features worked as intended (sprinklers were not fully tested, but everything else looked good).
**Consistency**: The naming conventions are consistent across the board.

However, there are a few areas to improve:

**Sprites**: The sprites have been imported with default settings, leading to a shadowy appearance. Consider using these import settings:
Shadow: 0%
Black threshold: 100%
(not set in stone - but these settings tend to work for me)
**Animation Adjustments**: In "Animation --> Scene," the alignment of the Willow tree cutting and rooting cutting is off when held by the female character. Please adjust the hold position—use the maple cutting as a reference point.
**Shears Transition**: Shears with only one use can't interact with Willow and Cypress trees. Please add a transition for the last use.
**Willow Tree Sprite**: The top part of the "Willow Tree in Tree Pit" has the wrong sprite—it has Bay Tree sprite at the top hiding in branches.

Awesome work overall, and we are excited to see these changes in action! Keep it up!

**Comment by SenMooo** [comment]
Thank you very much for testing! All of the issues noted are addressed and fixed.

**Comment by zabala6** [comment]
Good job. I couldn't find any bugs. Finally we will be able to replant swamp!

**Comment by risvh** [comment]
Merging https://github.com/twohoursonelife/OneLifeData7/pull/151 instead

**Pull request closed without merging**
