### PR TITLE
Remove decors from bowler and top hats

### PR DESCRIPTION
**Pull request by zabala6**
Adds possibility to remove roses and feather from undyed bowler and top hats. 
**Implementing suggestion**: ability to remove decoration from white hats 
It is possible to implement this functionality for colored hats also thanks to using categories.

### CODE REVIEW

**Review by sidraba — CHANGES_REQUESTED** [review]
I'm so happy to finally be able to color my white hats! They have been waiting for long time to be colorful! Thank you so much for working on this!

Found only these issues:
1. When using Shears use 2 then hats have no cutting sound
2. Shears to not use uses when cutting objects from hats.

**Comment by SenMooo** [comment]
Very nice change indeed. Tested as well and found nothing new to report. Nice work :)

**Comment by zabala6** [comment]
Thank you for testing. 

I fixed the issues:
- When using Shears use 2 then hats have no cutting sound
- Shears to not use uses when cutting objects from hats

**Review by risvh — APPROVED** [review]
Thanks, please add the colored hats too

**Pull request merged**
