### PR TITLE
Add possibility to grow lotus in a barrel

### PR DESCRIPTION
**Pull request by sidraba**
What it contains:

1. make cuttings from lotus and root them.
2. plant cuttings in full water barrels.
3. planted lotus go through planted cutting - sprout - budding - mature life stages (30 min in total).
4. you get rid of grown lotus in barrel by shearing it twice.
5. Barrels now have two more uses: 
  - growing lotus, 
  - they act same way as cisterns and can contain 5 buckets of water and you can use both bucket and watering can on it.

Todo:

- [x] cleanup of sounds
- [x] Shears with Lotus Cutting doesn't have a last use transition
- [x] Held pos of Rooting Lotus Cutting vs Lotus Cutting (see maple cutting in contrast)
- [x] Shearing and rooting steps should use the categories 14035 and 14038
- [x] Full Wooden Barrel with Water#just built, should be renamed "just trimmed" or "just sheared" or some other names
- [x] There is the black dot and some leftover shadow at the top in the sprite LotusInBarrel 121341
- [x] Empty Watering Can cannot be used on (last use) Partial Wooden Barrel with Water
- [x] Rename "of water" instead of "with water"

### CODE REVIEW

**Comment by risvh** [comment]
- Shears with Lotus Cutting doesn't have a last use transition
- Held pos of Rooting Lotus Cutting vs Lotus Cutting (see maple cutting in contrast)
- Shearing and rooting steps should use the categories 14034, 9041, 9042, 9043
- Full Wooden Barrel with Water#just built, should be renamed "just trimmed" or "just sheared" or some other names
- There is the black dot and some leftover shadow at the top in the sprite LotusInBarrel 121341
- Empty Watering Can cannot be used on (last use) Partial Wooden Barrel with Water

**Comment by sidraba** [comment]
> * Shearing and rooting steps should use the categories 14034, 9041, 9042, 9043
9043 is Planted (dry) cutting trees and flower. I cannot use it for lotus as lotus is not planted in the ground and is never in dry stage. Any advice on that?

**Comment by sidraba** [comment]
> * Held pos of Rooting Lotus Cutting vs Lotus Cutting (see maple cutting in contrast)

Held position is consistent with other flowers (see dandelion, england ivy or snake plant as examples. Any advice on this?

**Comment by risvh** [comment]
> > * Held pos of Rooting Lotus Cutting vs Lotus Cutting (see maple cutting in contrast)
> 
> Held position is consistent with other flowers (see dandelion, england ivy or snake plant as examples. Any advice on this?

Go to Scene page, spawn a character, make it hold 1794, then make it hold 9036. The green part stays in the same position. Forget about the flower cuttings. You can make the green part of the lotus cutting stays in the same position as well. (23712 vs 23713)

**Comment by risvh** [comment]
> > * Shearing and rooting steps should use the categories 14034, 9041, 9042, 9043
> >   9043 is Planted (dry) cutting trees and flower. I cannot use it for lotus as lotus is not planted in the ground and is never in dry stage. Any advice on that?

As we've tried in the stream, rooting doesn't work (14034, 9041, 9042, 9043), it assumes the cutting would be planted on soil.
But still we can use 14035 and 14038 for the shear cutting action.

**Comment by sidraba** [comment]
Fixed all issues mentioned.

**Comment by sidraba** [comment]
Fixed hold position for cuttings, as discussed in discord.

**Review by risvh — APPROVED** [review]

**Pull request merged**
